#!/usr/bin/env bash
# scripts/link.sh - create live symlinks so supported hosts read this workspace copy directly.
set -euo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"
HOST="${1:-both}"

run_first_time_setup() {
 local config_path="${USING_MEMORY_CONFIG:-$HOME/.skills/using-memory/config.yaml}"
 if [ "${USING_MEMORY_SKIP_SETUP:-0}" = "1" ]; then
  echo "Skipping memory storage setup because USING_MEMORY_SKIP_SETUP=1"
  return
 fi
 if [ -f "$config_path" ]; then
  echo "Memory storage config already exists: $config_path"
  return
 fi
 if [ -t 0 ]; then
  echo "No memory storage config found. Starting first-time setup."
  python3 "$HERE/scripts/memory_tool.py" setup
 else
  echo "No memory storage config found: $config_path"
  echo "Run this later to configure memory storage path, remote Git repo, namespace, and machine ID:"
  echo "  python3 $HERE/scripts/memory_tool.py setup"
 fi
}

print_hook_next_steps() {
 local codex_home="${CODEX_HOME:-$HOME/.codex}"
 local claude_home="${CLAUDE_HOME:-$HOME/.claude}"
 echo
 echo "Hook wiring targets:"
 echo "  Codex SessionStart/UserPromptSubmit/PostToolUse/PreCompact/Stop:"
 echo "    python3 ${codex_home}/skills/using-memory/scripts/hooks/codex_memory_hook.py"
 echo "  Claude Code SessionStart:"
 echo "    python3 ${claude_home}/skills/using-memory/scripts/hooks/claude_session_start_hook.py"
 echo "  Claude Code UserPromptSubmit/PostToolUse/PostToolBatch/ConfigChange/PreCompact/Stop:"
 echo "    python3 ${claude_home}/skills/using-memory/scripts/hooks/claude_memory_hook.py"
 echo "Rerun scripts/install.sh or scripts/link.sh after updates so new hook helpers are deployed."
}

# Install the `umem` CLI wrapper into ~/.local/bin, pointing at this source
# working copy (link.sh keeps hosts reading the live checkout). Thin shell
# wrapper, not a symlink — see the note in install.sh.
install_umem_wrapper() {
 local target="$1"
 local bindir="${UMEM_BIN_DIR:-$HOME/.local/bin}"
 local wrapper="$bindir/umem"
 mkdir -p "$bindir"
 cat > "$wrapper" <<EOF
#!/usr/bin/env bash
# Auto-generated by using-memory install.sh/link.sh — thin CLI wrapper.
# Equivalent to: python3 <skill>/scripts/memory_tool.py <args>
exec python3 "$target/scripts/memory_tool.py" "\$@"
EOF
 chmod +x "$wrapper"
 echo
 echo "Installed 'umem' CLI: $wrapper"
 echo "  -> python3 $target/scripts/memory_tool.py"
 case ":${PATH}:" in
  *":$bindir:"*) echo "  Ready. Try: umem --help" ;;
  *) echo "  NOTE: $bindir is not on PATH. Add it, then run 'umem --help':"
     echo "        export PATH=\"$bindir:\$PATH\"" ;;
 esac
}

link_host() {
 local name="$1"
 local dest="$2"
 echo "Linking $name: $HERE -> $dest"
 mkdir -p "$(dirname "$dest")"
 if [ -e "$dest" ] && [ ! -L "$dest" ]; then
  echo "refusing to replace existing directory: $dest" >&2
  echo "Remove it manually or run scripts/install.sh for a copied install." >&2
  exit 2
 fi
 ln -sfn "$HERE" "$dest"
}

case "$HOST" in
 codex)
 link_host "codex" "${CODEX_HOME:-$HOME/.codex}/skills/using-memory"
 ;;
 claude-code)
 link_host "claude-code" "${CLAUDE_HOME:-$HOME/.claude}/skills/using-memory"
 ;;
 both)
 link_host "codex" "${CODEX_HOME:-$HOME/.codex}/skills/using-memory"
 link_host "claude-code" "${CLAUDE_HOME:-$HOME/.claude}/skills/using-memory"
 ;;
 *)
 echo "Usage: $0 [codex|claude-code|both]" >&2
 exit 2
 ;;
esac

run_first_time_setup
print_hook_next_steps
install_umem_wrapper "$HERE"
